[package]
name = "forklift"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
async-channel = "1.8.0"
base16 = "0.2.1"
bytes = "1.3.0"
crc32fast = "1.3.2"
fastbloom-rs = "0.3.1"
futures = "0.3.25"
hyper = { version = "0.14.23", features = ["full"] }
hyper-tls = "0.5.0"
miniz_oxide = { version = "0.6.2", features = ["simd"] }
multiqueue2 = "0.1.7"
rkyv = "0.7.39"
sha2 = "0.10.6"
sled = { version = "0.34.7", features = ["compression"] }
thiserror = "1.0.38"
time = { version = "0.3.17", default-features = false, features = ["formatting", "std"] }
tokio = { version = "1.23.0", features = ["full"] }
url = "2.3.1"
urlencoding = "2.1.2"
uuid = { version = "1.2.2", default-features = false, features = ["v4", "fast-rng"] }
zstd = "^0.9.0"
