folder = "catgirl-crawl"

[crawl]
base_url = "https://cat-girl.gay"
urls_file = "cat-girl.txt"

[http]
workers = 4
tasks_per_worker = 16

[output]
workers = 2
file_prefix = "catgirl-gay-"
file_size = "1GB"

[index]
compression = true
compression_level = 5
overwrite = true

[script_manager]
workers = 2

[scripts.html]
filter = { mime_types = ["text/html"] }
command = "python"
args = ["scripts/scrape_html.py"] 

[scripts.links]
filter = { mime_types = ["text/css"] }
command = "python"
args = ["scripts/scrape_css.py"] 